export enum AccessType {
  ADMITTED,
  REQUESTED,
  REQUEST_REJECTED ,
  INVITED ,
  INVITE_REJECTED ,
  LEFT,
  BLOCKED_COMMUNITY,
  KICKED,
  BANNED,
  NONE,
}

export const ACCESS_TYPE_ARRAY_ENUM: string[] = [
  "ADMITTED",
  "REQUESTED",
  "REQUEST_REJECTED",
  "INVITED",
  "INVITE_REJECTED",
  "LEFT",
  "BLOCKED_COMMUNITY",
  "KICKED",
  "BANNED",
  "NONE",
];
